[project]
name = "fleet-commander"
version = "0.1.0"
description = "Fleet Commander"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
 "arcade>=3.3.3",
 "gymnasium>=1.2.2",
 "numpy>=2.3.4",
 "pypresence>=4.3.0",
]
